// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with output of `flutterfire configure` for project soka-planner
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC96DzJYuZNV7-aOhevG-j-ijz7H2Fy2Lo',
    authDomain: 'soka-planner.firebaseapp.com',
    projectId: 'soka-planner',
    storageBucket: 'soka-planner.firebasestorage.app',
    messagingSenderId: '777301808825',
    appId: '1:777301808825:web:af2218099b72f386bf2d68',
    measurementId: 'G-YMRQ0LVSLQ',
  );

  // TODO: Replace with output of `flutterfire configure` for project soka-planner
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACie_9C1lrNTPqyBoUeoEr2KBE-hqIquM',
    authDomain: 'soka-planner.firebaseapp.com',
    projectId: 'soka-planner',
    storageBucket: 'soka-planner.firebasestorage.app',
    messagingSenderId: '777301808825',
    appId: '1:777301808825:android:4f0d3cb32f74866fbf2d68',
    measurementId: 'G-YMRQ0LVSLQ',
  );
}
